import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HeroSection from "../components/HeroSection";
import Divider from "../components/Divider";
import DragonAffordable from "../components/DragonAffordable";
import ClientDragon from "../components/ClientDragon";
import FaqDragon from "../components/FaqDragon";
import ImportantDragon from "../components/ImportantDragon";
import ChoosingDragon from "../components/ChoosingDragon";
import DragonSlider from "../components/DragonSlider";
import { useRouter } from "next/router";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../config/firebase";
import { useEffect, useState } from "react";

export default function Home() {

  const router = useRouter();
  const [userData,setUserData]=useState();

  const logoutHandler = async () => {
    await auth.signOut();
    router.push("/login");
  };

  // useEffect(() => {
  //   const timer = setTimeout(() => {
  //     auth.signOut().then((res) => {
  //     });
  //   }, 300000);
  //   return () => clearTimeout(timer);
  // }, []);

  useEffect(() => {
   const unsub= onAuthStateChanged(auth, (user) => {
      if (!user) {
        setUserData("")
      }
      else{
        setUserData(user)
      }
    });
    return ()=>unsub()
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Dragon Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar userData={userData} />
        <HeroSection  userData={userData} />
        <Divider />
        <DragonAffordable userData={userData} />
        <ChoosingDragon userData={userData} />
        <DragonSlider userData={userData} />
        <ClientDragon userData={userData} />
        <FaqDragon userData={userData}  />
        <ImportantDragon userData={userData} />
        <Footer userData={userData}  />
      </main>
    </div>
  );
}
